"""Fix UserPermission relationship

Revision ID: cffcd4e1629f
Revises: 82a00c3731fb
Create Date: 2025-10-01 17:07:33.358348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cffcd4e1629f'
down_revision: Union[str, None] = '82a00c3731fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
